---

- hosts: localhost
  tasks: 
  - name: "install zsh"
    become: ansible_distribution != 'MacOSX'
    package: 
      name: zsh
      state: latest
  - name: "find zsh"
    shell: "which zsh"
    register: which_zsh
  - name: "Get username"
    shell: "whoami"
    register: whoami
  - name: "Set zsh as default shell"
    become: yes
    user: 
      name: "{{ whoami.stdout }}"
      shell: "{{ which_zsh.stdout }}"
  - name: "Check if Oh-My-Zsh installed"
    stat:
      path: "~/.oh-my-zsh"
    register: oh_my_zsh_dir
  - name: "Install Oh My Zsh"
    block:
    - name: "Download Oh-My-Zsh install.sh"
      get_url:
        url: "https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
        dest: "/tmp/oh-my-zsh-install.sh"
        mode: 0755
    - name: "Run Oh-My-Zsh install.sh"
      script: "/tmp/oh-my-zsh-install.sh"
    when: not oh_my_zsh_dir.stat.exists
